In [1]:
import pandas as pd
import numpy as np

In [3]:
df1=pd.read_csv('F:/Python/Ostad Python/Jupyter notebook/NB_NLP_HAM-SPAM_Identification/fake_and_real/fake_and_real_news.csv')
df1

Text label
0      Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1     U.S. conservative leader optimistic of common ...  Real
2     Trump proposes U.S. tax overhaul, stirs concer...  Real
3      Court Forces Ohio To Allow Millions Of Illega...  Fake
4     Democrats say Trump agrees to work on immigrat...  Real
...                                                 ...   ...
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...  Fake
9896  Trump consults Republican senators on Fed chie...  Real
9897  Trump lawyers say judge lacks jurisdiction for...  Real
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...  Fake
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...  Fake

[9900 rows x 2 columns]

In [5]:
df1.label.value_counts()

label
Fake    5000
Real    4900
Name: count, dtype: int64

In [7]:
df1.shape

(9900, 2)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df1.Text, df1.label, test_size=0.2, random_state=42)

In [11]:
X_train

1665    As new fiscal year dawns, hope for Illinois bu...
1416    Schumer says U.S. budget deal doable if Trump ...
7298    NRA calls for more regulation after Vegas shoo...
4700    White House says Tillerson to remain as secret...
6192     Scientists Scramble To Copy Climate Data Befo...
                              ...                        
5734     WATCH: Hannity Loses His Sh*t And Refers To H...
5191     Sean Hannity Just Showed EXACTLY How Delusion...
5390     WATCH: CNN Host Makes Trump’s Campaign Manage...
860     Democratic senator lifts hold on Trump antitru...
7270    'Unremarkable' Virginia attacker shows difficu...
Name: Text, Length: 7920, dtype: object

In [13]:
X_test

8432     Trump’s Involvement In Houston Chemical Plant...
5680    U.S. Senate votes near unanimously for Russia,...
4767    White and male: broader bureaucracy mirrors Tr...
9218    Trump, Modi call North Korea's 'grave threat' ...
621      Ivanka Trump Shares Famous Jewish Quote, But ...
                              ...                        
9500    Kid Rock hints online he will run for U.S. Sen...
5858    U.S. Justice Department not looking to charge ...
7442     WATCH: Nicolle Wallace Just Ripped Trump A Ne...
2846    Trump budget would sell entire U.S. Northeast ...
1468    Seeking end to boycott, North Carolina rescind...
Name: Text, Length: 1980, dtype: object

In [15]:
y_train

1665    Real
1416    Real
7298    Real
4700    Real
6192    Fake
        ... 
5734    Fake
5191    Fake
5390    Fake
860     Real
7270    Real
Name: label, Length: 7920, dtype: object

In [17]:
y_test

8432    Fake
5680    Real
4767    Real
9218    Real
621     Fake
        ... 
9500    Real
5858    Real
7442    Fake
2846    Real
1468    Real
Name: label, Length: 1980, dtype: object

In [19]:
X_train.values

array(['As new fiscal year dawns, hope for Illinois budget dims CHICAGO (Reuters) - Risking a historic drop to junk bond status, Illinois began its third straight fiscal year without a budget on Saturday as political maneuvering dimmed hopes for a bipartisan spending and revenue package anytime soon. While the House scheduled session on Sunday to take up a revenue package, the Senate is not slated to return until Monday. The nation’s fifth-largest state has lacked a full operating budget since July 2015 and is under a warning from S&P that it will drop Illinois’ creditworthiness to the lowest of any state in history if it fails to pass a fiscal 2018 budget that starts to address a chronic structural deficit. Talks between Democrats who control the Illinois House and Republicans had shown signs of progress as both sides rallied behind a $36.5 billion spending blueprint on Friday and were poised to build on that positive movement in a rare Fourth of July holiday weekend legislative sessi

In [21]:
X_train.values.shape

(7920,)

In [23]:
type(X_train.values)

numpy.ndarray

## Create bag of words representation using CountVectorizer OR BEGAPOD METHOD

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<7920x52816 sparse matrix of type '<class 'numpy.int64'>'
	with 1745278 stored elements in Compressed Sparse Row format>

In [26]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
X_train_cv.shape

(7920, 52816)

In [31]:
X_train_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
#ALL ROW  52816 FOLLOW CODE
v.get_feature_names_out()

array(['00', '000', '0000', ..., 'zzzzaaaacccchhh', 'zzzzzzzzzzzzz',
       'émigré'], dtype=object)

In [35]:
pd.DataFrame(X_train_cv.toarray(), columns=v.get_feature_names_out())

00  000  0000  00007  00042  0005  000s  001  00155  0019  ...  zyklon  \
0      0    0     0      0      0     0     0    0      0     0  ...       0   
1      0    0     0      0      0     0     0    0      0     0  ...       0   
2      0    0     0      0      0     0     0    0      0     0  ...       0   
3      0    0     0      0      0     0     0    0      0     0  ...       0   
4      0    0     0      0      0     0     0    0      0     0  ...       0   
...   ..  ...   ...    ...    ...   ...   ...  ...    ...   ...  ...     ...   
7915   0    0     0      0      0     0     0    0      0     0  ...       0   
7916   0    0     0      0      0     0     0    0      0     0  ...       0   
7917   0    0     0      0      0     0     0    0      0     0  ...       0   
7918   0    0     0      0      0     0     0    0      0     0  ...       0   
7919   0    0     0      0      0     0     0    0      0     0  ...       0   

      zypries  zyries  zz  zzbluecomet  zzsg90pbf6  zztaine  zzzzaaaacccchhh  \
0           0       0   0            0           0        0                0   
1           0       0   0            0           0        0                0   
2           0       0   0            0           0        0                0   
3           0       0   0            0           0        0                0   
4           0       0   0            0           0        0                0   
...       ...     ...  ..          ...         ...      ...              ...   
7915        0       0   0            0           0        0                0   
7916        0       0   0            0           0        0                0   
7917        0       0   0            0           0        0                0   
7918        0       0   0            0           0        0                0   
7919        0       0   0            0           0        0                0   

      zzzzzzzzzzzzz  émigré  
0                 0       0  
1                 0       0  
2                 0       0  
3                 0       0  
4                 0       0  
...             ...     ...  
7915              0       0  
7916              0       0  
7917              0       0  
7918              0       0  
7919              0       0  

[7920 rows x 52816 columns]

In [37]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [41]:
X_test

8432     Trump’s Involvement In Houston Chemical Plant...
5680    U.S. Senate votes near unanimously for Russia,...
4767    White and male: broader bureaucracy mirrors Tr...
9218    Trump, Modi call North Korea's 'grave threat' ...
621      Ivanka Trump Shares Famous Jewish Quote, But ...
                              ...                        
9500    Kid Rock hints online he will run for U.S. Sen...
5858    U.S. Justice Department not looking to charge ...
7442     WATCH: Nicolle Wallace Just Ripped Trump A Ne...
2846    Trump budget would sell entire U.S. Northeast ...
1468    Seeking end to boycott, North Carolina rescind...
Name: Text, Length: 1980, dtype: object

#### SIMILARLY DO BEGAPOD FOR X_TEST

In [43]:
X_test_cv = v.transform(X_test)

In [45]:
X_test_cv.toarray().shape

(1980, 52816)

In [47]:
model.score(X_test_cv, y_test)

0.9777777777777777

In [49]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        Fake       0.98      0.98      0.98       973
        Real       0.98      0.98      0.98      1007

    accuracy                           0.98      1980
   macro avg       0.98      0.98      0.98      1980
weighted avg       0.98      0.98      0.98      1980



## Now Input new prediction data for fake news 

In [51]:
email_dataset = [
    "Residents of New York City reported seeing strange lights in the sky last night, with some speculating that they were extraterrestrial beings. Scientists have yet to confirm or deny the sightings, but social media is abuzz with excitement.",
    "A groundbreaking study from a little-known research institute claims that chocolate, specifically dark chocolate, can cure cancer. Experts have raised concerns about the lack of peer-reviewed research to support these findings.",
    "NASA scientists have confirmed the discovery of a new exoplanet located in the habitable zone of its star. The planet has water, raising hopes of finding extraterrestrial life in the near future.",
    "Elon Musk has unveiled a detailed roadmap for SpaceX’s mission to colonize Mars by 2030. The ambitious project will involve sending multiple spacecraft to the red planet and establishing a permanent human presence.",
    "Experts predict that a new ice age will begin in 2025 due to shifts in the Earth's magnetic poles and climate patterns. Authorities are urging people to prepare for drastic weather changes."
]    

In [53]:
emails_count = v.transform(email_dataset)
emails_count.toarray().shape

(5, 52816)

In [55]:
emails_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [57]:
#emails_count.toarray().shape
model.predict(emails_count)

array(['Fake', 'Real', 'Real', 'Real', 'Real'], dtype='<U4')